networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
    depends_on:
      - postgres
      - backend
      - frontend
    networks:
      - dev

  backend:
      build:
        context: ./backend
      env_file:
        - ./backend/.env
      depends_on:
        - postgres
      networks:
        - dev
  
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      DB_HOST: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env.production
    depends_on:
      - postgres
      - backend
    networks:
      - dev

volumes:
  postgres_data:
