name: CI/CD Roam The World
on:
  push:
    branches:
      - dev

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Ruff
        - uses: astral-sh/ruff-action@v2
