"""Add users, locations, and tracks tables

Revision ID: 1b41f7405232
Revises: a34d04d9a795
Create Date: 2024-12-10 12:05:01.719394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b41f7405232'
down_revision: Union[str, None] = 'a34d04d9a795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
