"""image_url in TrackModels

Revision ID: a34d04d9a795
Revises: 73be0566c4b2
Create Date: 2024-12-09 11:40:11.542276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a34d04d9a795'
down_revision: Union[str, None] = '73be0566c4b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_column('tracks', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tracks', 'image_url')
    # ### end Alembic commands ###
